plantjungle/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

import home_app.views
from home_app.views import HomeView

from plant_app import views as plant_views
from home_app import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_views.HomeView.as_view(), name='home-view'),
    path('plant-description/<slug:category>/<slug:plant>/', plant_views.PlantView.as_view(), name='plant-view'),
    #path('check-price/', plant_views.check_price),
    path('categories/', plant_views.CategoryView.as_view(), name='all-categories-list'),
    #path('plant-add/', plant_views.PlantAddView.as_view()),
    path('plants/', plant_views.PlantListView.as_view(), name='all-plants-list'),
    path('search-result/', plant_views.SearchResultView.as_view(), name='search-result'),
    path('plant-filter/', plant_views.FilterPlantView.as_view(), name='plant-filter'),
    path('plant-filter/', plant_views.FilterPlantView.as_view(), name='plant-filter-result'),
    path('category/<slug>/', plant_views.ChosenCategoryView.as_view(), name='chosen-category'),
    path('room-part/<slug>/', plant_views.ChosenRoompartView.as_view(), name='chosen-roompart'),
    path('home-room/<slug>/', plant_views.ChosenHomeroomView.as_view(), name='chosen-homeroom'),
    path('window-side/<slug>/', plant_views.ChosenWindowsideView.as_view(), name='chosen-windowside'),
    path('influence/<str:data>/', plant_views.ChosenInfluenceView.as_view(), name='chosen-influence'),
    path('add-user/', home_views.AddUserView.as_view(), name='add-user'),
    path('login/', home_views.LoginView.as_view(), name='login'),
    path('logout/', home_views.log_out, name='logout'),
    path('create-my-profile/', home_views.CreateProfileView.as_view(), name='create-my-profile'),
    path('edit-my-profile/', home_views.EditProfileView.as_view(), name='edit-my-profile'),
    path('my-profile/', home_views.UserProfileView.as_view(), name='my-profile'),
    path('change-password/', home_views.ResetPasswordView.as_view(), name='change-password'),
    path('my-wishlist/', plant_views.AddToWishlistView.as_view(), name='my-wishlist'),
    path('my-plants/', plant_views.AddToMyplantsView.as_view(), name='my-plants'),
    path('my-view-plants/delete-wishlist/<slug>/', plant_views.DeletePlantWishlistView.as_view(), name='delete-plant-wishlist'),
    path('my-view-plants/delete-plants/<slug>/', plant_views.DeletePlantPlantsView.as_view(), name='delete-plant-plants'),
    path('price-compare/<slug>/', plant_views.PriceCompareView.as_view(), name='price-compare'),
    #path('logout/', home_views.ResetPasswordView.as_view(), name='logout'),
    #path('plant-filter-results/', plant_views.FilterPlantView.as_view(), name='plant-filter-results'),
    #path('plant-spider/', plant_views.PlantSpider),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plant_app/models.py
from django.db import models
from django.utils.text import slugify
from scrapy_djangoitem import DjangoItem


WORLD_DIRECTIONS = (
    (1, 'okno w kierunku wschodnim'),
    (2, 'okno w kierunku zachodnim'),
    (3, 'okno w kierunku północnym'),
    (4, 'okno w kierunku południowym')
)

HOME_ROOM = (
    (1, 'kuchnia'),
    (2, 'łazienka'),
    (3, 'pokój dzienny/ sypialnia'),
)

ROOM_PART = (
    (1, 'zacieniony kąt'),
    (2, 'słoneczny parapet'),
)

ANIMAL_INFLUENCE = (
    (1, 'szkodliwa dla zwierząt'),
    (2, 'przyjazna dla zwierząt'),
)

AIR_PURIFYING = (
    (1, 'oczyszczające powietrze'),
    (2, 'brak wpływu na oczyszczanie powietrza'),
)

ROOM_DESCRIPTION = (
    (1, 'Jeśli do tej pory nawet nie myślałeś ustawieniu roślin na kuchennym blacie z obawy o niekorzystne warunki tam panujące, mamy dla ciebie dobre wieści. Istnieje całkiem pokaźna lista roślin, którym bardzo odpowiada gorąca para, podwyższona wilgotność'),
    (2, 'Żywe kwiaty w łazience? Tak, to możliwe. Wbrew pozorom rośliny dobrze się czują w łazience, szczególnie te pochodzące z ciepłych i wilgotnych regionów. Wilgotny, ciepły i często zaciemniony klimat panujący w łazience to idealne warunki wzrostu dla wielu roślin doniczkowych. Czasem nawet zdecydowanie lepsze niż te panujące w pokojach, gdzie zbyt dużo światła i suche powietrze nie są korzystne dla wielu gatunków.'),
    (3, 'Pokój dzienny to na ogół miejsce tętniące życiem. Rośliny powinny więc być jak najbardziej zróżnicowane, ciekawe i kolorowe. Pokój dzienny, a także nasze sypialnie są jednak z reguły pomieszczeniami nieco bardziej suchymi niz pozostałe części naszego mieszkania. Jakie rośliny pasują do nich najlepiej?'),
)

WINDOWSIDE_DESCRIPTION = (
    (1, 'Parapety okien wychodzących na wschód, podobnie jak tych zachodnich, zaledwie przez kilka godzin w ciągu dnia są w pełni nasłonecznione, przez resztę dnia oferując światło rozproszone. Sprawdzą się tu odmiany, które nie wymagają długotrwałego naświetlania do prawidłowego wzrostu.'),
    (2, 'Okno kwiatowe od zachodniej strony, podobnie jak wschodnie, nasłonecznione jest przez mniejszą część dnia. W tym przypadku promienie słoneczne padają bezpośrednio na rośliny po południu i wczesnym wieczorem. Czas ekspozycji na światło słoneczne jest więc podobny, przy czym okno zachodnie jest zdecydowanie cieplejsze niż wschodnie. Wiosną i latem promienie są dodatkowo dosyć silne, przez co mogą sparzyć liście delikatnych odmian. Które rośliny doniczkowe wybrać zatem na okno zachodnie? Którym niestraszne jest chwilowe zacienienie? Na parapecie zachodnim dobrze czuć się będą rośliny preferujące półcień lub lekkie nasłonecznienie.'),
    (3, 'Parapet okna skierowanego na północ to miejsce, w którym najtrudniej uprawiać rośliny domowe. Dlaczego? Przez większość dnia stojące na nim kwiaty nie mają bezpośredniego kontaktu z promieniami słonecznymi, otrzymując jedynie rozproszone, bardzo delikatne światło. Warunki takie są nieodpowiednie dla odmian o kolorowych liściach, które do rozwoju potrzebują większej ilości chlorofilu produkowanego w wyniku fotosyntezy. Nie sprawdzi się tu również większość doniczkowych roślin kwitnące, które zawiązują pączki kwiatowe wyłącznie przy dobrym nasłonecznieniu. Jakie więc rośliny uprawiać przy zachodnim oknie? Zasada jest prosta – sprawdzą się tu przede wszystkim odporne odmiany o ciemnozielonych liściach.'),
    (4, 'Okna południowe są najbardziej nasłonecznione, a przez to niemal równie wymagające przy uprawie roślin jak zacienione okna północne. Dlaczego? Większość roślin domowych nie akceptuje bezpośredniego silnego nasłonecznienia, które oferuje okno z wystawą południową. Efektem postawienia na parapecie południowym zbyt delikatnej rośliny może być jej zwiędnięcie z przesuszenia lub sparzenie liści. Warunki panujące na parapecie okna południowego można porównać do klimatu pustynnego, gdzie jest sucho i bardzo słonecznie. Jakie zatem kwiaty doniczkowe wybrać na południowe okno?')
)


ROOMPART_DESCRIPTION = (
    (1, 'Zacieniony kąt to warunki nieodpowiednie dla odmian o kolorowych liściach, które do rozwoju potrzebują większej ilości chlorofilu produkowanego w wyniku fotosyntezy. Nie każda roślina znosi więc silne promieniowanie.'),
    (2, 'Ustawiając kwiaty doniczkowe na parapecie okiennym trzeba uwzględnić to, że podczas wietrzenia – zwłaszcza zimą – chłodne powietrze może zagrażać roślinom, natomiast latem trzeba uważać, aby silnie operujące w dzień promienie słoneczne nie spowodowały poparzeń liści.'),
)

ANIMAL_INFLUENCE_DESCRIPTION = (
    (1, 'Nie masz zwierząt? Negatywny wpływ roślin nie stanowi dla Ciebie problemu? Wybierz roślinę która zauroczy cię pięknym wyglądem, bez konieczności zwracania uwagi na inne czynniki.'),
    (2, 'Boisz się, że rośliny będą szkodliwe dla Twojego ukochanego zwierzaka. Wybierz rośliny doniczkowe bezpieczne dla kota i psa. Nie zawierają one trujących związków więc nawet jak Twój pupil potraktuje je jako przekąskę, nadal będzie czuł się dobrze i zachowa zdrowie. Stwórz miejską dżunglę bez obawy o ich zdrowie zwierząt.')
)

AIRPURIFYING_DESCRIPTION = (
    (1, 'Rośliny oczyszczające powietrze to niesłabnący trend ostatnich lat. Przełomowe w tym kierunku okazały się być badania instytutu NASA, które zwieńczono raportem przedstawiającym ranking roślin najlepiej oczyszczających powietrze. Agencja kosmiczna nie bez powodu zainteresowała się tym tematem. Szukano bowiem sposobu na łatwe, skuteczne i nie wymagające energii elektrycznej oczyszczanie powietrza w promach i na stacjach kosmicznych. Finalnie rośliny ze względu na swoje specyficzne wymagania nie zagościły w kosmosie. Jednak wyniki przeprowadzonych badań wiralowo rozeszły się po świecie skłaniając coraz to większe rzesze ludzi do zainteresowania się tematem i kupna roślin oczyszczających powietrze.'),
    (2, 'Nie zależy Ci na właściwościach oczyszających powietrze przez rośliny? Spokojnie możesz przejżeć wszystkie poniższe pozycje.')
)


# Class Model for creating Category objects table
class Category(models.Model):
    name = models.CharField(max_length=225)
    description = models.TextField(blank=True)
    picture = models.ImageField(null=True, blank=True, upload_to="images/")  # dwa opcjonalne argument - height_field i width_field
    slug = models.SlugField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name

    # function that return slug on basis of self.name of creating object
    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


# Class Model for creating Plant objects talbe
class Plant(models.Model):
    name = models.CharField(max_length=225)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    description = models.TextField()
    picture = models.ImageField(null=True, blank=True, upload_to="images/")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    watering_description = models.TextField()
    solar_description = models.TextField()
    influence = models.IntegerField(choices=ANIMAL_INFLUENCE, default=1, null=True)
    purifying = models.IntegerField(choices=AIR_PURIFYING, default=1, null=True)
    slug = models.SlugField(max_length=50, blank=True, null=True)
    search_key = models.CharField(max_length=25, blank=True)


    def __str__(self):
        return self.name

    # function that return slug on basis of self.name of creating object
    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


# Class Model for creating WindowSide objects table
class WindowSide(models.Model):
    direction = models.IntegerField(choices=WORLD_DIRECTIONS)
    plants = models.ManyToManyField(Plant, related_name='window_sides')
    slug = models.SlugField(max_length=50, blank=True, null=True)
    description = models.IntegerField(choices=WINDOWSIDE_DESCRIPTION, null=True)

    def __str__(self):
        return self.get_direction_display()

    # function that return slug on basis of self.name of creating object
    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.get_direction_display())
        super().save(*args, **kwargs)


# Class Model for creating HomeRoom objects table
class HomeRoom(models.Model):
    room = models.IntegerField(choices=HOME_ROOM)
    plants = models.ManyToManyField(Plant, related_name='home_room')
    slug = models.SlugField(max_length=50, blank=True, null=True)
    description = models.IntegerField(choices=ROOM_DESCRIPTION, null=True)

    def __str__(self):
        return self.get_room_display()

    # function that return slug on basis of self.name of creating object
    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.get_room_display())
        super().save(*args, **kwargs)


# Class Model for creating RoomPart objects table
class RoomPart(models.Model):
    roompart = models.IntegerField(choices=ROOM_PART)
    plants = models.ManyToManyField(Plant, related_name='room_part')
    slug = models.SlugField(max_length=50, blank=True, null=True)
    description = models.IntegerField(choices=ROOMPART_DESCRIPTION, null=True)

    def __str__(self):
        return self.get_roompart_display()

    # function that return slug on basis of self.name of creating object
    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.get_roompart_display())
        super().save(*args, **kwargs)


#Class Model for creating ScrapyJungleBoogie objects table
class ScrapyJungleBoogie(models.Model):
    name = models.CharField(max_length=225)
    link = models.TextField(blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    picture = models.TextField(blank=True, null=True)

templates/plant_app/all_categories.html
{% extends "../base.html" %}

{% block app_head %}Wybierz gatunek którego szukasz{% endblock %}

{% csrf_token %}

{% block content %}
    <style>
.pagination {
  display: inline-block;
}

.pagination a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
}
    </style>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Kategoria</th>
      <th scope="col">Zdjęcie</th>
    </tr>
  </thead>
  <tbody>
      {% for category in page.object_list %}
    <tr>
      <th scope="row">{{ page.start_index|add:forloop.counter0 }}</th>
      <td> <a class="nav-link text-secondary" href="{% url 'chosen-category' category.slug %}"> {{ category.name }}</td>
        {% if category.picture.url %}
      <td><img width="200" height="200" class="img-thumbnail" src="{{ category.picture.url }}/"></td>
        {% endif %}
    </tr>
   </a>
  {% endfor %}
  </tbody>
  </div>
    </div>
</table>
    <div class="pagination">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">< poprzednia</a>
        {% endif %}
      {% for pg in page.paginator.page_range %}
            <a href="?page={{pg}}">{{pg}}</a>
      {% endfor %}
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">następna ></a>
        {% endif %}
</div>
{% endblock %}

templates/plant_app/category.html
{% extends "../base.html" %}

{% block app_head %}Kategoria: {{ choosen_category.name }} {% endblock %}

{% csrf_token %}

{% block content %}
 {% if choosen_category %}
<p> {{ choosen_category.description }}</p>
 {% endif %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Roślina</th>
      <th scope="col">Gatunek</th>
      <th scope="col">Zdjęcie</th>
    </tr>
  </thead>
  <tbody>
      {% for plant in choosen_plants %}
      <th scope="row">{{ forloop.counter }}</th>
      <td> <a class="nav-link text-secondary" href="{% url 'plant-view' plant.category.slug plant.slug %}"> {{ plant.name }}</td>
      <td>{{ plant.category.name }}</td>
        {% if plant.picture.url %}
      <td><img width="120" height="120" class="img-thumbnail" src="{{ plant.picture.url }}/"></td>
        {% endif %}
    </tr>
    </a>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/plant_app/delete_plant_plants.html
{% extends "../base.html" %}

{% block app_head %}Usuń roślinę z profilu: {{ searched_value }} {% endblock %}


{% block content %}
<form class="d-flex" method="POST">
      {% csrf_token %}
    <div>
<a> Czy na pewno chcesz usunąć z moich roślin: {{ plant.name }} ?</a>
    </div>
    <div>
        <br>
        <input class="btn btn-success form-check-inline" name="delete" type="submit" value="Tak">
        <input class="btn btn-success form-check-inline" name="delete" type="submit" value="Nie">
        </br>
    </div>
</form>
{% endblock %}

templates/plant_app/home_room.html
{% extends "../base.html" %}

{% block app_head %} Kategoria: {{ choosen_homeroom.get_room_display }} {% endblock %}

{% csrf_token %}

{% block content %}
<p> {{ choosen_homeroom.get_description_display }}</p>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Roślina</th>
      <th scope="col">Gatunek</th>
      <th scope="col">Zdjęcie</th>
    </tr>
  </thead>
  <tbody>
      {% for plant in choosen_plants %}
      <th scope="row">{{ forloop.counter }}</th>
      <td> <a class="nav-link text-secondary" href="{% url 'plant-view' plant.category.slug plant.slug %}">{{ plant.name }}</td>
      <td>{{ plant.category.name }}</td>
        {% if plant.picture.url %}
      <td><img width="120" height="120" class="img-thumbnail" src="{{ plant.picture.url }}/"></td>
        {% endif %}
    </tr>
   </a>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/plant_app/my_plants.html
{% extends "../base.html" %}

{% block app_head %}Moje rośliny: {% endblock %}



{% block content %}
<form class="d-flex" method="POST">
  {% csrf_token %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Roślina</th>
      <th scope="col">Gatunek</th>
      <th scope="col">Zdjęcie</th>
    </tr>
  </thead>
  <tbody>
      {% for plant in my_plants %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td> <a class="nav-link text-secondary" href="{% url 'plant-view' plant.category.slug plant.slug %}"> {{ plant.name }}</td>
      <td>{{ plant.category.name }}</td>
        {% if plant.picture.url %}
      <td><img width="120" height="120" class="img-thumbnail" src="{{ plant.picture.url }}/"></td>
      <td><a class="btn btn-success" aria-current="page" href="{% url 'delete-plant-plants' plant.slug %}">Usuń z moich roślin</a></td>
        {% endif %}
    </tr>
    </a>
       {% empty %}
          <tr>
            <td colspan="4">Brak wyników wyszukiwania</td>
          </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/plant_app/my_wishlist.html
{% extends "../base.html" %}

{% block app_head %}Moja wishlista: {% endblock %}

{% block content %}
<form class="d-flex" method="POST">
  {% csrf_token %}
<table class="table table-hover">
    {% csrf_token %}
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Roślina</th>
      <th scope="col">Gatunek</th>
      <th scope="col">Zdjęcie</th>
    </tr>
  </thead>
  <tbody>
      {% for plant in wishlist %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td> <a class="nav-link text-secondary" href="{% url 'plant-view' plant.category.slug plant.slug %}"> {{ plant.name }}</td>
      <td>{{ plant.category.name }}</td>
        {% if plant.picture.url %}
      <td><img width="120" height="120" class="img-thumbnail" src="{{ plant.picture.url }}/"></td>
      <td><a class="btn btn-success" aria-current="page" href="{% url 'delete-plant-wishlist' plant.slug %}">Usuń z wishlisty</a></td>
      <td><a class="btn btn-success" aria-current="page" href="{% url 'price-compare' plant.slug %}">Porównaj cenę</a></td>
        {% endif %}
    </tr>
    </a>
       {% empty %}
          <tr>
            <td colspan="4">Brak wyników wyszukiwania</td>
          </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/plant_app/plant-description.html
{% extends "../base.html" %}

{% block app_head %}Opis rośliny{% endblock %}

{% csrf_token %}

{% block content %}

    <p> Nazwa rośliny: {{ plant.name }} </p>
    <p> Nazwa kategorii: <b>{{ plant.category.name }}</b> </p>
    <p> Opis: {{ plant.description}} </p>
    {% if plant.picture.url %}
    <p> <img width=600 height=600 src="{{ plant.picture.url }}/"> </p>
    {% endif %}
    <p> Podlewanie: {{ plant.watering_description}} </p>
    <p> Nasłonecznienie: {{ plant.solar_description}} </p>
    <p> Wpływ na rośliny: <b> {{ plant.get_influence_display }} </b> </p>
    <p> Wpływ na powietrze: <b> {{ plant.get_purifying_display }} </b> </p>
    <p> Najlepiej wybrać pomieszczenie z oknem w kierunku: </p>
        {% for element in window_side %}
    <br> <b> {{ element.get_direction_display }} </b> </br>
        {% endfor %}
    </p>
        <p> Najlepsze pomieszczenia w mieszkaniu to: </p>
        {% for element in homeroom %}
    <br> <b> {{ element.get_room_display }} </b> </br>
        {% endfor %}
    </p>
        <p> Gdzie w pomieszczeniu będzie mu najlepiej: </p>
        {% for element in roompart %}
    <br> <b> {{ element.get_roompart_display }} </b> </br>
        {% endfor %}
    </p>
     <form method="post" enctype='multipart/form-data'>
         {% csrf_token %}
     {% if request.user.is_authenticated %}
        <input class="btn btn-success" name="wishlist" type="submit" value="Dodaj do wishlisty">
        <input class="btn btn-success" name="my-plants" type="submit" value="Dodaj do moich roślin">
    {% endif %}
     </form>

{% endblock %}

templates/plant_app/plant_filter.html
{% extends "../base.html" %}

{% block app_head %}Wybierz czego szukasz:{% endblock %}

{% block content %}
    {{msg}}
    <form action="{% url 'plant-filter' %}" method="POST">
      {% csrf_token %}
      {{ form }}
   <div class="d-grid gap-2 d-md-block">
      <input class="btn btn-success" type="submit" value="Szukaj"  %}">
   </form>
        {% if category %}
        {{ category }}
        {% endif %}
{% endblock %}

templates/plant_app/plant_filter_result.html
{% extends "../base.html" %}

{% block app_head %}Przefiltrowane wyniki: {% endblock %}

{% csrf_token %}

{% block content %}
<form class="d-flex" method="POST" action="{% url 'plant-filter-result' %}">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Roślina</th>
      <th scope="col">Gatunek</th>
      <th scope="col">Zdjęcie</th>
    </tr>
  </thead>
  <tbody>
      {% for element in all_plants %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td> <a class="nav-link text-secondary" href="{% url 'plant-view' element.category.slug element.slug %}">{{ element.name }}</td>
      <td>{{ element.category.name }}</td>
        {% if element.picture.url %}
      <td><img width="120" height="120" class="img-thumbnail" src="{{ element.picture.url }}/"></td>
        {% endif %}
    </tr>
      {% empty %}
      {% for plant in plants %}
    <tr>
      <th scope="row">{{ page.start_index|add:forloop.counter0 }}</th>
      <td> <a class="nav-link text-secondary" href="{% url 'plant-view' plant.category.slug plant.slug %}"> {{ plant.name }}</td>
      <td>{{ plant.category.name }}</td>
        {% if plant.picture.url %}
      <td><img width="120" height="120" class="img-thumbnail" src="{{ plant.picture.url }}/"></td>
        {% endif %}
    </tr>
    </a>
  {% endfor %}
  </tbody>
  {% endfor %}
  </tbody>
</table>
</form>
{% endblock %}

templates/plant_app/plant_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dodawnanie roślin</title>
</head>
<body>
<div class ="form-group"></div>
  <form method="post" enctype='multipart/form-data'>
    {% csrf_token %}
      <p>DODAWANIE NOWEJ ROŚLINY</p>

      <table>
      {{ joongle.name.1 }}
      {5 joongle.picture.url.1 %}
      </table>
    <input type="submit" value="Tak" />
  </form>
</div>
</body>
</html>

templates/plant_app/room_part.html
{% extends "../base.html" %}

{% block app_head %} Kategoria: {{ choosen_roompart.get_roompart_display }} {% endblock %}

{% csrf_token %}

{% block content %}
<p> {{ choosen_roompart.get_description_display }}</p>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Roślina</th>
      <th scope="col">Gatunek</th>
      <th scope="col">Zdjęcie</th>
    </tr>
  </thead>
  <tbody>
      {% for plant in choosen_plants %}
      <th scope="row">{{ forloop.counter }}</th>
      <td><a class="nav-link text-secondary" href="{% url 'plant-view' plant.category.slug plant.slug %}">{{ plant.name }}</td>
      <td>{{ plant.category.name }}</td>
        {% if plant.picture.url %}
      <td><img width="120" height="120" class="img-thumbnail" src="{{ plant.picture.url }}/"></td>
        {% endif %}
    </tr>
   </a>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/plant_app/window_side.html
{% extends "../base.html" %}

{% block app_head %} Kategoria: {{ choosen_windowside.get_direction_display }} {% endblock %}

{% csrf_token %}

{% block content %}
<p> {{ choosen_windowside.get_description_display }}</p>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Roślina</th>
      <th scope="col">Gatunek</th>
      <th scope="col">Zdjęcie</th>
    </tr>
  </thead>
  <tbody>
      {% for plant in choosen_plants %}
      <th scope="row">{{ forloop.counter }}</th>
      <td> <a class="nav-link text-secondary" href="{% url 'plant-view' plant.category.slug plant.slug %}">{{ plant.name }}</td>
      <td>{{ plant.category.name }}</td>
        {% if plant.picture.url %}
      <td><img width="120" height="120" class="img-thumbnail" src="{{ plant.picture.url }}/"></td>
        {% endif %}
    </tr>
   </a>
  {% endfor %}
  </tbody>
</table>

{% endblock %}